"""
Build the data file for the Multifamily Housing dashboard.

Reads the "Aff and WF parcels" spreadsheet (one row per housing record; a
parcel can appear more than once when it has, for example, an existing
record plus a permitted-not-constructed record) and writes a compact JS
data file that LongRange/html/multifamily-housing.html loads with a
<script> tag. A <script> tag is used instead of fetch() so the page also
works when opened directly from disk (file://).

Usage (arcgispro-py3):
    python LongRange/scripts/build_multifamily_data.py "C:/path/to/Aff and WF parcels.xlsx"

Optional:
    --out LongRange/data/multifamily_parcels.js
"""

import argparse
import json
import logging
import re
from datetime import date
from pathlib import Path

import pandas as pd

log = logging.getLogger("build_multifamily_data")

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "LongRange" / "data" / "multifamily_parcels.js"

# Spreadsheet column -> output key. Order here is the row array order.
COLUMNS = [
    ("APN", "apn"),
    ("Jurisdiction", "juris"),
    ("Units", "units"),
    ("Year Built", "yearBuilt"),
    ("COUNTY_LANDUSE_DESCRIPTION", "landUse"),
    ("Affordable and Workforce", "affwf"),
    ("Timing", "timing"),
    ("Type", "type"),
    ("Project Notes", "notes"),
]

MIN_PLAUSIBLE_YEAR = 1850

# Records with a blank Timing are permitted or proposed units that have not been
# constructed yet (per Mason, 2026-09-09). Give them an explicit label so the page can
# count them in the pipeline and show them in the Timing filter.
TIMING_BLANK_FILL = "Permitted or Proposed - Not Constructed"

# APNs in the spreadsheet that have been retired or renumbered since the record was
# entered. Left side is the spreadsheet value, right side is the current APN in the
# Parcels service. Records keep their attributes; only the APN changes.
APN_REMAP = {
    "029-170-001": "029-170-008",   # CSLT, 75 reserved affordable bonus units (confirmed by Mason 2026-09-09)
    "015-032-029": "015-032-030",   # El Dorado County, 2-unit multifamily (confirmed by Mason 2026-09-09)
    "093-041-006": "093-041-008",   # Placer County: 093-041-004 and 093-041-006 were merged into 093-041-008.
                                    # TRPA verified 2 residential units (duplex) plus some commercial on the merged
                                    # 093-041-008, so the 2 units carry forward (Mason, 2026-09-09).
}


def clean_text(value):
    """Strip, collapse internal whitespace, and normalize blanks to None."""
    if pd.isna(value):
        return None
    text = re.sub(r"\s+", " ", str(value)).strip()
    return text or None


def clean_year(value):
    if pd.isna(value):
        return None
    try:
        year = int(round(float(value)))
    except (TypeError, ValueError):
        return None
    if year < MIN_PLAUSIBLE_YEAR or year > date.today().year + 5:
        return None
    return year


def clean_units(value):
    if pd.isna(value):
        return 0
    try:
        return int(round(float(value)))
    except (TypeError, ValueError):
        return 0


def build(xlsx_path: Path, out_path: Path) -> None:
    log.info("Reading %s", xlsx_path)
    df = pd.read_excel(xlsx_path)

    missing = [src for src, _ in COLUMNS if src not in df.columns]
    if missing:
        raise SystemExit(f"Spreadsheet is missing expected columns: {missing}")

    rows = []
    for rec in df.to_dict("records"):
        apn = clean_text(rec["APN"])
        if not apn:
            log.warning("Skipping row with blank APN: %s", rec)
            continue
        if apn in APN_REMAP:
            log.info("Remapping APN %s -> %s", apn, APN_REMAP[apn])
            apn = APN_REMAP[apn]
        row = [
            apn,
            clean_text(rec["Jurisdiction"]),
            clean_units(rec["Units"]),
            clean_year(rec["Year Built"]),
            clean_text(rec["COUNTY_LANDUSE_DESCRIPTION"]),
            clean_text(rec["Affordable and Workforce"]),
            clean_text(rec["Timing"]) or TIMING_BLANK_FILL,
            clean_text(rec["Type"]),
            clean_text(rec["Project Notes"]),
        ]
        rows.append(row)

    n_apns = len({r[0] for r in rows})
    total_units = sum(r[2] for r in rows)
    log.info("%d records, %d unique APNs, %d units", len(rows), n_apns, total_units)

    payload = {
        "generated": date.today().isoformat(),
        "source": xlsx_path.name,
        "columns": [key for _, key in COLUMNS],
        "rows": rows,
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    header = (
        "// Generated by LongRange/scripts/build_multifamily_data.py -- do not edit by hand.\n"
        f"// Source: {xlsx_path.name}  Generated: {payload['generated']}\n"
    )
    out_path.write_text(header + "window.MF_DATA = " + body + ";\n", encoding="utf-8")
    log.info("Wrote %s (%.1f KB)", out_path, out_path.stat().st_size / 1024)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("xlsx", type=Path, help="Path to the Aff and WF parcels spreadsheet")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output .js path")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    build(args.xlsx, args.out)


if __name__ == "__main__":
    main()
